config/routes.rb
Rails.application.routes.draw do
  resources :articles
  root "articles#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title,presence: true
    validates :body,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    add_flash_types :success, :info, :warning, :danger
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, {only: [:edit,:show,:update,:destroy]}
  add_flash_types :success, :info, :warning, :danger
  
  def index
    @article=Article.order(created_at: :desc)
  end

  def show

  end

  def edit
  end

  def new
    @article=Article.new
  end


  def create
    @article=Article.new(article_params)
    if @article.save
      redirect_to @article, success: "作成しました"
    else
      flash.now[:danger]= "作成失敗"
      render :new 
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article, success: "更新しました"
    else
       falsh.now[:danger]= "更新失敗"
       render :edit
    end
  end

  def destroy
    if @article.destroy
       
      redirect_to root_path, success:"削除に成功"
    else
      flash.now[:danger]= "削除に失敗"
      redirect_to root_path 
    end
  end

  private

  def find_article
    @article=Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for article do |f|%>
            <div class="form-group p-t-15">
                <%=f.label :title, "タイトル"%>
                <%= f.text_field :title, class:"form-control"%>
            </div>

            <div class="form-group">
                    <%=f.label :body, "内容"%>
                <%= f.text_area :body,rows: 10, class:"form-control"%>
            </div>
    
            <%=f.submit class:"btn btn-primary"%>
            <%end%>

app/views/articles/edit.html.erb
<!DOCTYPE html>

<div class="container">

    <div class="col-md-12 m-t-5 article-block ">
        <h1　class="text-center"> 編集</h1>
        <%= image_tag 'chill.jpg', class:"article-image p-t-15"%>
        
        <div class="p-b-15">
            <%=render "form", article:@article%>
            
        </div>
    </div>
    
    </div>

app/views/articles/index.html.erb
<!DOCTYPE html>
<div class="container">
        
    <div class="row">
    
    <% @article.each do |a|%>
    <%=link_to a do%>
    <div class="col-md-3 m-t-5 article-block ">
    
    <%= image_tag 'chill.jpg', class:"img-responsive padding-top-15"%>
    <div>
        <p class="title"><%=a.title%></p>
        <span class="p-b-15">
        <%=a.created_at.strftime("%Y年%m月%d日 %H時%M分")%>
        </span>
        </div>
    </div>
    <%end%>
    <%end%>
    </div>
    <div class="row">
        <%=link_to "新規作成",new_article_path, class:" m-t-5 btn btn-primary"%>
    </div>
    </div>

app/views/articles/new.html.erb
<!DOCTYPE html>

<div class="container">

    <div class="col-md-12 m-t-5 article-block ">
        <h1 > 新規作成</h1>
        <%= image_tag 'chill.jpg', class:"article-image p-t-15"%>
        
        <div class="p-b-15">
            <%=render "form", article:@article%>
            
        </div>
    </div>
    
    </div>

app/views/articles/show.html.erb
<!DOCTYPE html>
      
<div class="container">

    <div class="col-md-12 m-t-5 article-block ">
            <h1 class="blog-title"> <%= @article.title %> </h1>
        <%= image_tag 'chill.jpg', class:"article-image p-t-15"%>
        
        <div class="p-b-15">
            <%=simple_format @article.body,class:"blog-body"%>
            
            <p class="text-right">
                <%=@article.created_at.strftime("%Y年%m月%d日 %H時%M分")%>
            </p>
        </div>

        <%=link_to "編集" ,edit_article_path(@article),class:"btn btn-primary",style:"margin-bottom:15px; margin-right:15px" %>
        <%=link_to "削除" ,article_path(@article),method: :delete,data: { confirm: '本当に削除してもよろしいですか？' },class:"btn btn-danger",style:"margin-bottom:15px" %>
    </div>
    
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>D's BLOG</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=10.0, user-scalable=yes">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   
    <header><nav class="navbar navbar-default navbar-fixed-top ">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navigation">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">KobaD's BLOG</a>
          </div>
          <div class="collapse navbar-collapse" id="navigation">
              <p class="navbar-text navbar-right">
                <%=link_to "新規作成" ,new_article_path%>
              </p>
            </div>
        </div>
      </nav></header>
      
      <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %> text-center"><%= message %></div>
    <% end %>
        
    <%= yield %>

    <footer class="bg-danger f-mar ">
        <ul class="list-inline text-center py-2">
            <li class="list-inline-item">
              <a href="/articles/new" class="text-white">Let's</a>
            </li>
            <li class="list-inline-item">
              <a href="/articles/new" class="text-white">Make</a>
            </li>
            <li class="list-inline-item">
              <a href="/articles/new" class="text-white">Your Blog</a>
            </li>
          </ul>
        <div class="text-white text-center pb-4">
          <p class="h2"><%=link_to "KobaD's BLOG","/" %></p>
          <small class="small">&copy;KobaD's BLOG</small>
        </div>
        
      </footer>

  </body>
</html>